---
- hosts: kubernetes
  become: true
  
  tasks:
    - name: delete old deployment
      shell: kubectl delete -f /home/centos/Deployment.yml
    - name: delete old service
      shell: kubectl delete -f /home/centos/Service.yml
    - name: create new deployment
      shell: kubectl apply -f /home/centos/Deployment.yml
    - name: create new service
      shell: kubectl apply -f /home/centos/Service.yml
