---
- hosts: kubernetes
  become: true
  tasks:
    - name: create new deployment
      shell: kubectl apply -f /home/centos/Deployment.yml
      args:
        executable: /tmp
    - name: create new service
      shell: kubectl apply -f /home/centos/Service.yml
      args:
        executable: /tmp
