---
- hosts: kubernetes
  become: true
  tasks:
    - name: create new deployment
      cmd: kubectl apply -f /home/ansadmin/Deployment.yml
    - name: create new service
      cmd: kubectl apply -f /home/ansadmin/Service.yml
