---
- hosts: kubernetes
  become: ansadmin
  tasks:
    - name: create new deployment
      shell: kubectl apply -f /home/centos/Deployment.yml
    - name: create new service
      shell: kubectl apply -f /home/centos/Service.yml
