---
- hosts: kubernetes
  become: true
  ignore_errors: true
  
  tasks:
    - name: create new deployment
      shell: kubectl apply -f /home/centos/Deployment.yml
    - name: create new service
      shell: kubectl apply -f /home/centos/Service.yml
