---
- hosts: kubernetes
  #become: true
  user: ansadmin
  
  tasks:
  - name: delete old deployment
    command: kubectl delete -f Deployment.yml
  - name: delete old service
    command: kubectl delete -f Service.yml
  - name: create new deployment
    command: kubectl apply -f Deployment.yml
  - name: create new service
    command: kubectl apply -f /home/ansadmin/Service.yml
